
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-09T12:06:19-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c40387d036f5a5276f2106037c6e0f8b4abbaae",
 "version": "5.0.0a11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
